/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_smartstudy_soundpoolcompat_AudioEngine */

#ifndef _Included_kr_co_smartstudy_soundpoolcompat_AudioEngine
#define _Included_kr_co_smartstudy_soundpoolcompat_AudioEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeInitilizeAudioEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeInitilizeAudioEngine
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeReleaseAudioEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeReleaseAudioEngine
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativePlayAudio
 * Signature: (IZF)I
 */
JNIEXPORT jint JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativePlayAudio
  (JNIEnv *, jclass, jint, jboolean, jfloat);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativePause
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeResume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeResume
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
