/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_smartstudy_soundpoolcompat_AudioSource */

#ifndef _Included_kr_co_smartstudy_soundpoolcompat_AudioSource
#define _Included_kr_co_smartstudy_soundpoolcompat_AudioSource
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_co_smartstudy_soundpoolcompat_AudioSource_INVALID_AUDIOID
#define kr_co_smartstudy_soundpoolcompat_AudioSource_INVALID_AUDIOID -1L
/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioSource
 * Method:    nativeCreateAudioSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioSource_nativeCreateAudioSource
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioSource
 * Method:    nativeReleaseAudioSource
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioSource_nativeReleaseAudioSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioSource
 * Method:    nativeSetAudioSourceFileDescriptor
 * Signature: (ILjava/io/FileDescriptor;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioSource_nativeSetAudioSourceFileDescriptor
  (JNIEnv *, jclass, jint, jobject, jlong, jlong);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioSource
 * Method:    nativeSetAudioSourceURI
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioSource_nativeSetAudioSourceURI
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
