/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_smartstudy_soundpoolcompat_AudioEngine */

#ifndef _Included_kr_co_smartstudy_soundpoolcompat_AudioEngine
#define _Included_kr_co_smartstudy_soundpoolcompat_AudioEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_VOICE
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_VOICE 0L
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_SYSTEM
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_SYSTEM 1L
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_RING
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_RING 2L
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_MEDIA
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_MEDIA 3L
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_ALARM
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_ALARM 4L
#undef kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_NOTIFICATION
#define kr_co_smartstudy_soundpoolcompat_AudioEngine_ANDROID_STREAM_NOTIFICATION 5L
/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeInitilizeAudioEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeInitilizeAudioEngine
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeReleaseAudioEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeReleaseAudioEngine
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativePlayAudio
 * Signature: (IIFIIF)I
 */
JNIEXPORT jint JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativePlayAudio
  (JNIEnv *, jclass, jint, jint, jfloat, jint, jint, jfloat);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativePause
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeResume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeResume
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativePauseAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativePauseAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeResumeAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeResumeAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeStopAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeStopAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeSetVolume
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeSetVolume
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeSetPlayRate
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeSetPlayRate
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     kr_co_smartstudy_soundpoolcompat_AudioEngine
 * Method:    nativeSetRepeatCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_kr_co_smartstudy_soundpoolcompat_AudioEngine_nativeSetRepeatCount
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
