/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_smartstudy_soundpoolcompat_AudioSource_OnCreateAudioSourceComplete */

#ifndef _Included_kr_co_smartstudy_soundpoolcompat_AudioSource_OnCreateAudioSourceComplete
#define _Included_kr_co_smartstudy_soundpoolcompat_AudioSource_OnCreateAudioSourceComplete
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
